version: '3.7'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 7540:7540/tcp # Built-in HTTP control server
# other containers ports
      - 8112:8112     # deluge webui
      - 58846:58846   # deluge daemon
      - 9117:9117     # jackett
      - 8191:8191     # flaresolverr
    volumes:
      - ${CONFIG_ROOT}/Gluetun:/gluetun
      - ${CONFIG_ROOT}/Gluetun/port_forward:/tmp/gluetun/forwarded_port
    environment:
       - VPNSP=mullvad
       - VPN_TYPE=openvpn
       - OPENVPN_USER=${MULLVAD_USER}
       - OPENVPN_PASSWORD=m
       - TZ=${TIMEZONE}
       - COUNTRY=UK
       - CITY=London
    restart: unless-stopped


  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DELUGE_LOGLEVEL=INFO #optional
    volumes:
      - ${CONFIG_ROOT}/Deluge:/config
      - ${DOWNLOADS_ROOT}:/downloads
#      - /shares/media:/media
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      - gluetun

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/Jackett:/config
      - ${DOWNLOADS_ROOT}:/downloads
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      - gluetun
      - flaresolverr
      
      
  jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       network_mode: bridge
       environment:
            - LOG_LEVEL=debug
            - TZ=${TIMEZONE}
       ports:
            - 5055:5055
       volumes:
            - ${CONFIG_ROOT}/Jellyseerr:/app/config
       restart: unless-stopped
      
  flaresolverr:
    container_name: flaresolverr
    image: 'ghcr.io/flaresolverr/flaresolverr:latest'
    environment:
      - LOG_LEVEL=info
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      - gluetun

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: bridge
    ports:
      - 7878:7878/tcp     # radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/Radarr:/config
      - ${MEDIA_ROOT}:/media
      - ${DOWNLOADS_ROOT}:/downloads
    restart: unless-stopped
    depends_on:
      - gluetun
      - jackett
      - deluge

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: bridge
    ports:
      - 8989:8989/tcp     # sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/Sonarr:/config
      - ${MEDIA_ROOT}:/media
      - ${DOWNLOADS_ROOT}:/downloads
    restart: unless-stopped
    depends_on:
      - gluetun
      - jackett
      - deluge



  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    network_mode: bridge
    ports:
      - 8096:8096/tcp     # jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/Jellyfin:/config
      - ${MEDIA_ROOT}:/media

    restart: unless-stopped
