version: '3.8'
services:
  #watchtower:
  #  image: containrrr/watchtower
  #  container_name: watchtower
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - /root/.docker/config.json:/config.json
  #  command: --interval 30

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/Heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
      
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 7540:7540/tcp # Built-in HTTP control server
# other containers ports
      - 8112:8112     # deluge webui
      - 58846:58846   # deluge daemon
      - 9117:9117     # jackett
      - 8191:8191     # flaresolverr
    volumes:
      - ${CONFIG_ROOT}/Gluetun:/gluetun
      - ${CONFIG_ROOT}/Gluetun/port_forward:/tmp/gluetun/forwarded_port
    environment:
       - VPNSP=mullvad
       - VPN_TYPE=openvpn
       - OPENVPN_USER=${MULLVAD_USER}
       - OPENVPN_PASSWORD=m
       - TZ=${TIMEZONE}
       - COUNTRY=UK
       - CITY=London
    restart: unless-stopped
    healthcheck:
      test: /gluetun-entrypoint healthcheck
      interval: 5s
      retries: 1
      start_period: 10s
      timeout: 5s

  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DELUGE_LOGLEVEL=INFO #optional
    volumes:
      - ${CONFIG_ROOT}/Deluge:/config
      - ${DOWNLOADS_ROOT}:/downloads
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      - gluetun
    healthcheck:
      test: curl --fail http://localhost:8112 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/Jackett:/config
      - ${DOWNLOADS_ROOT}:/downloads
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      - gluetun
      - flaresolverr
    healthcheck:
      test: curl --fail http://localhost:9117 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       network_mode: bridge
       environment:
            - LOG_LEVEL=debug
            - TZ=${TIMEZONE}
       ports:
            - 5055:5055
       volumes:
            - ${CONFIG_ROOT}/Jellyseerr:/app/config
       restart: unless-stopped
       healthcheck:
         test: wget --no-verbose --tries=1 --spider http://localhost:5055 || exit 1
         interval: 60s
         retries: 5
         start_period: 20s
         timeout: 10s
      
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      - gluetun
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8191 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: bridge
    ports:
      - 7878:7878/tcp     # radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/Radarr:/config
      - ${MEDIA_ROOT}:/media
      - ${DOWNLOADS_ROOT}:/downloads
    restart: unless-stopped
    depends_on:
      - gluetun
      - jackett
      - deluge
    healthcheck:
      test: curl --fail http://localhost:7878 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: bridge
    ports:
      - 8989:8989/tcp     # sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/Sonarr:/config
      - ${MEDIA_ROOT}:/media
      - ${DOWNLOADS_ROOT}:/downloads
    restart: unless-stopped
    depends_on:
      - gluetun
      - jackett
      - deluge
    healthcheck:
      test: curl --fail http://localhost:8989 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: bridge
    ports:
      - 8096:8096/tcp     # jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/Jellyfin:/config
      - ${MEDIA_ROOT}:/media
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8096 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    ports:
      - 8581:8581/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: 1
    healthcheck:
      test: curl --fail http://localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
